import {icon,external} from './shared.mjs';
const arrow=icon('arrow-up-right');
const albumCard=(root,id,title,artist,role)=>`<article class="album-card"><a href="${root}music/?release=${id}" class="album-art"><img src="${root}assets/${id}.webp" width="600" height="600" alt="${title} by ${artist} cover artwork" loading="lazy"><span>Explore the record ${arrow}</span></a><div class="album-caption"><div><h3><a href="${root}music/?release=${id}">${title}</a></h3><p>${artist}</p></div><span>${id==='pills'?'2022':'2021'}</span></div><p class="album-role">${role}</p></article>`;
export function home(root){return `
<section class="home-hero" aria-labelledby="home-title"><div class="hero-image"><img src="${root}assets/portrait.webp" alt="Joel Bobby at a studio mixing console" width="1100" height="1255" fetchpriority="high"></div><div class="hero-content"><h1 id="home-title" aria-label="Joel Bobby"><span class="name-line"><span>Joel</span></span><span class="name-line"><span>Bobby<span class="name-dot">.</span></span></span></h1><p class="hero-profession">Musician. Producer. Engineer.</p><p>From the first bass line <br>to the final mix.</p><div class="hero-actions"><button class="button preview-trigger" data-preview="pills:2" disabled aria-label="Play Ninde Koode preview"><span class="preview-icon">${icon('play')}</span><span class="preview-label">Play a preview</span></button><a class="plain-link" href="about/">Meet Joel ${arrow}</a></div></div><div class="hero-baseline"><span>Recording · Mixing · Bass guitar · Live sound</span><a href="#selected-recordings" class="scroll-link">Explore the work ${icon('arrow-down')}</a><span>Brooklyn, NY</span></div></section>
<section class="home-intro wrap"><p>In the studio. <br>On the stage.</p><div><h2>A musician’s ear,<br>on both sides of the glass.</h2><p>Joel’s work moves between playing bass, producing records, and engineering live sound. From independent releases in India to sessions in Brooklyn, the music comes first.</p><a class="text-link" href="about/">The person behind the sound ${arrow}</a></div></section>
<section class="home-records wrap" id="selected-recordings"><div class="section-heading"><h2>Selected recordings</h2><a class="text-link" href="music/">All music & credits ${arrow}</a></div><div class="album-grid">${albumCard(root,'pills','Pills','Joash Mathew','Bass · Production · Recording · Mixing')}${albumCard(root,'azad','Azad Panchi','Roohani','Bass · Recording · Pre-mix engineering')}</div></section>
<section class="home-live"><div class="wrap home-live-inner"><div><h2>When the<br>room comes alive.</h2><p>Live sessions, front-of-house mixes, and the work behind a show.</p><a class="text-link" href="live/">Explore live work ${arrow}</a></div><a class="home-live-poster" href="live/"><img src="${root}assets/freightliner.webp" alt="Shaantanu and the Renaissance Faire concert poster" width="320" height="320" loading="lazy"><div><span>Live at The Base, Pune</span><strong>Freightliner</strong><span>Engineering · Recording · Mixing ${arrow}</span></div></a></div></section>`;}

export function music(root){return `
<section class="page-heading wrap"><h1>Made to<br>be heard.</h1><div><p>Selected recordings</p><p>Bass, production, recording, and mixing.<br>Explore Joel’s role in each release.</p></div></section>
<section class="music-section wrap" aria-label="Listen to recordings"><div class="release-selector" role="group" aria-label="Choose a release"><button data-release="pills" aria-pressed="true"><img src="${root}assets/pills.webp" alt="" width="54" height="54"><span>Pills<small>Joash Mathew · 2022</small></span>${arrow}</button><button data-release="azad" aria-pressed="false"><img src="${root}assets/azad.webp" alt="" width="54" height="54"><span>Azad Panchi<small>Roohani · 2021</small></span>${arrow}</button></div>
<div class="listening-room" id="listening-room" aria-busy="true"><div class="sleeve-wrap"><img id="release-art" src="${root}assets/pills.webp" alt="Pills by Joash Mathew cover artwork" width="600" height="600"></div><div class="record-info"><div class="record-title"><h2 id="release-title">Pills</h2>${icon('vinyl-record')}</div><p id="release-byline">Joash Mathew · 2022</p><p id="release-role" class="role">Bass guitar · Production · Recording · Mixing</p><div id="track-list" class="track-list"><p>Loading track previews…</p></div><p class="preview-note">30-second previews · Courtesy of Apple Music</p><div class="record-links"><a id="release-link" class="text-link" href="https://music.apple.com/us/album/pills-ep/1629320900" ${external}>Full release on Apple Music ${arrow}</a><a id="spotify-link" href="https://open.spotify.com/album/3hYOUXULuY5LHDTxv20VtQ" ${external} aria-label="Listen to Pills on Spotify">${icon('spotify-logo')}</a></div><p id="press-note" class="press-note">Pills featured in <a href="https://rollingstoneindia.com/fresh-indie-fridays-54/" ${external}>Rolling Stone India’s Fresh Indie Fridays ${arrow}</a></p></div></div>
<noscript><p>Listen to <a href="https://music.apple.com/us/album/pills-ep/1629320900">Pills</a> or <a href="https://music.apple.com/us/album/azad-panchi-single/1580552229">Azad Panchi</a> on Apple Music. Enable JavaScript for previews.</p></noscript>
<article class="additional-project"><img src="${root}assets/kl316.webp" alt="KL316 remote music project artwork" width="320" height="320" loading="lazy"><div><h2>KL316</h2><p>A remote recording project created during Covid-19, sharing recording techniques and bringing a song together virtually.</p><span>Production & mixing</span><a class="text-link" href="https://www.youtube.com/watch?v=L8fVX3Kk6Bc" ${external}>Watch the project ${arrow}</a></div></article></section>`;}

const credits=[
 ['Clear Water','Tony Moreno’s students · NYU Open House, 2025','Live console mix','https://sites.google.com/nyu.edu/mtechopenhouse25/recording-critique'],
 ['StarClan (live)','Sharon Hurvitz · 2025','Mixing','https://sharonhurvitzmusic.com/'],
 ['Oceans of Slumber','A Passage Through the Veil · Studio G, 2024','Assistant engineering'],
 ['Dwight & Nicole','Live at Studio G','Assistant engineering'],
 ['Corinne Bailey Rae','The NYU Garage · 2024','Stage hand & venue engineering'],
 ['The Juniper Suite','Nicki Sekhar · The NYU Garage, 2024','Tech, mixing & engineering'],
 ['MTech Invasion 2 & 3','The NYU Garage, Brooklyn','Tech, mixing & engineering'],
 ['Take Me Back','Atharva Patwardhan · Swig KP, 2022','Tech, mixing & engineering']
];
export function live(root){return `
<section class="page-heading wrap"><h1>Sound in<br>the room.</h1><div><p>Live work</p><p>On stage, at the console,<br>and everywhere in between.</p></div></section>
<section class="live-content wrap"><article class="live-feature"><div class="live-poster"><img src="${root}assets/freightliner.webp" alt="Shaantanu and the Renaissance Faire concert poster for The Base, Pune" width="320" height="320"></div><div class="live-copy"><h2>Freightliner</h2><p class="artist-line">Shaantanu & the Renaissance Faire</p><p class="project-type">The Base, Pune · 2022</p><p>An hour-long live set in Pune, recorded and mixed from the desk.</p><dl><div><dt>Joel’s role</dt><dd>Live engineering<br>Recording & mixing</dd></div></dl><a class="button" href="https://www.youtube.com/watch?v=vHFrimG7u5g" ${external}>Watch the session ${icon('play')}</a></div></article>
<div class="live-pair"><article><img src="${root}assets/siddharth.webp" alt="Siddharth Kota Collective performance artwork" width="320" height="320" loading="lazy"><div><h2>Siddharth Kota Collective</h2><p>SoundTrackCafe, Pune · 2023</p><p>Live engineering, mixing & post-production</p><a class="text-link" href="https://www.instagram.com/p/CttJ2j6toWN/" ${external}>View the performance ${arrow}</a></div></article><article><img src="${root}assets/open-secret.webp" alt="The Last Words concert artwork" width="320" height="320" loading="lazy"><div><h2>The Last Words</h2><p>Open Secret · Mumbai & Pune, 2023</p><p>Front-of-house & technical production</p><a class="text-link" href="https://www.instagram.com/opensecretofficial/" ${external}>Explore Open Secret ${arrow}</a></div></article></div>
<div class="credit-heading"><h2>Further credits</h2><p>Selected studio sessions and live work.</p></div><div class="credits-list">${credits.map(([name,context,role,link])=>`<article><h3>${name}</h3><p>${context}</p><span>${role}</span>${link?`<a href="${link}" ${external} aria-label="Read the ${name} credit">${arrow}</a>`:'<span aria-hidden="true"></span>'}</article>`).join('')}</div></section>`;}

export function about(root){return `
<section class="about-feature wrap"><div class="about-photo"><img src="${root}assets/portrait.webp" alt="Joel Bobby smiling at a recording studio console" width="1100" height="1255"></div><div class="about-copy"><h1>Behind<br>the sound.</h1><p class="lead">Joel Bobby is a bassist, record producer, and studio & live engineer working across music and sound.</p><p>His work connects independent music in India with recording studios and live spaces in New York. On releases by Joash Mathew and Roohani, that means playing bass as well as shaping the recording.</p><p>At Studio G and NYU’s Brooklyn venues, his credits range from assistant engineering to live mixing and technical production.</p><a class="text-link" href="https://www.linkedin.com/in/joelbobby/" ${external}>Joel on LinkedIn ${arrow}</a></div></section>
<section class="guitar-section" id="bass" aria-labelledby="guitar-title"><div class="wrap guitar-layout"><div class="guitar-copy"><h2 id="guitar-title">It starts<br>with the bass.</h2><p>Bass guitar is part of Joel’s work on <em>Pills</em> and <em>Azad Panchi</em>. Playing and producing meet in the same place: the recording.</p><a class="text-link" href="${root}music/">Hear the records ${arrow}</a><p class="guitar-caption">An interactive study of a four-string bass.</p></div><div class="guitar-viewer" data-guitar><div class="guitar-stage" tabindex="0" role="group" aria-label="Interactive 3D bass guitar" aria-describedby="guitar-instructions"><img class="guitar-poster" src="${root}assets/3d/bass-poster.png" alt="Amber four-string bass guitar with a rosewood fingerboard and nickel hardware" width="760" height="760" loading="lazy"></div><noscript><p>Enable JavaScript to rotate the bass.</p></noscript><div class="guitar-bar"><p id="guitar-instructions" class="guitar-status" role="status">Drag to rotate once the model loads.</p><div class="guitar-controls" aria-label="Guitar view controls"><button type="button" data-guitar-left aria-label="Rotate guitar left" disabled>${icon('arrow-up-right')}</button><button type="button" data-guitar-right aria-label="Rotate guitar right" disabled>${icon('arrow-up-right')}</button><button type="button" data-guitar-reset disabled>Reset</button><button type="button" data-guitar-spin aria-pressed="false" disabled>Auto rotate</button></div></div></div></div></section>
<section class="practice-section wrap"><div class="section-heading"><h2>A practice<br>built around music.</h2><p>Playing, recording, and listening<br>inform the same work.</p></div><div class="practice-list"><article><h3>Musicianship</h3><p>Bass guitar on independent releases, including <a href="${root}music/?release=pills">Pills</a> and <a href="${root}music/?release=azad">Azad Panchi</a>.</p></article><article><h3>Recording & production</h3><p>From remote collaborations to studio sessions. Production, recording, and mixing with the artist’s work at the center.</p></article><article><h3>Live sound</h3><p>Front-of-house, technical production, and live recording across venues in Pune, Mumbai, and Brooklyn.</p></article></div></section>
<section class="research-section"><div class="wrap research-inner"><h2>Exploring how<br>we listen.</h2><div><p>Joel’s NYU work includes a live ensemble recording presented at the 2025 Music Technology Open House and a networked performance connecting musicians across institutions.</p><a class="text-link" href="https://sites.google.com/nyu.edu/mtechopenhouse25/recording-critique" ${external}>Clear Water · NYU Open House ${arrow}</a><a class="text-link" href="https://www.sarahweaver.org/42725-nyu-network-arts-event" ${external}>Network Arts · April 2025 ${arrow}</a></div></div></section>`;}

export function contact(){return `
<section class="contact-page wrap"><div class="contact-copy"><h1>Let’s make<br>something<br>worth hearing.</h1><p>Tell Joel about your record, live set,<br>or next collaboration.</p><a class="contact-email" href="mailto:joeljoshuabobby@gmail.com">joeljoshuabobby@gmail.com ${arrow}</a><div class="copy-line"><button id="copy-email">${icon('copy')} Copy email address</button><span id="copy-status" role="status"></span></div><div class="contact-socials"><a href="https://www.instagram.com/joel_bobby_009/" ${external}>Instagram ${arrow}</a><a href="https://www.linkedin.com/in/joelbobby/" ${external}>LinkedIn ${arrow}</a></div></div>
<form id="project-form" class="project-form"><h2>What are you working on?</h2><p>This opens a draft in your email app.</p><div class="form-row"><label>Your name<input name="name" autocomplete="name" required maxlength="100" placeholder="Name"></label><label>Your email<input name="email" type="email" autocomplete="email" required maxlength="180" placeholder="you@example.com"></label></div><label>Project type<select name="project"><option>Recording & production</option><option>Mixing</option><option>Bass guitar</option><option>Live sound</option><option>Something else</option></select></label><label>A little about the project<textarea name="message" rows="5" required maxlength="3000" placeholder="The music, the idea, and any dates you have in mind."></textarea></label><button class="button" type="submit">Open email draft ${arrow}</button><p class="form-note">Nothing is sent from this website. You can review your message before sending it.</p><p id="form-status" role="status"></p></form></section>`;}
