export const icon = name => `<i class="ph ph-${name}" aria-hidden="true"></i>`;
export const external = 'target="_blank" rel="noopener noreferrer"';
export const routes = ['home','music','live','about','contact'];
export const meta = {
 home:['Joel Bobby — Musician, Producer & Audio Engineer','Music, recording and live sound by Joel Bobby. Explore selected recordings, live credits and projects, or get in touch.'],
 music:['Music & Recordings — Joel Bobby','Listen to Pills by Joash Mathew and Azad Panchi by Roohani. Bass, production, recording and mixing credits by Joel Bobby.'],
 live:['Live Work & Engineering Credits — Joel Bobby','Selected live recordings and engineering work by Joel Bobby, from Pune and Mumbai to Studio G and NYU in Brooklyn.'],
 about:['About — Joel Bobby','Meet Joel Bobby, a bassist, record producer, and studio and live engineer working across independent music and sound.'],
 contact:['Contact — Joel Bobby','Get in touch with Joel Bobby about a record, live show, recording session or musical collaboration.']
};
export const url = (page, root) => page==='home' ? root : `${root}${page}/`;
export function shell(page, content) {
 const root=page==='home'?'./':'../'; const [title,description]=meta[page];
 const nav=routes.map((r,i)=>`<a href="${url(r,root)}" ${r===page?'aria-current="page"':''}>${['Home','Music','Live work','About','Contact'][i]}${r==='contact'?icon('arrow-up-right'):''}</a>`).join('');
 return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta name="theme-color" content="#171916"><link rel="canonical" href="https://parthawe.github.io/joel-bobby/${page==='home'?'':page+'/'}"><meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="https://parthawe.github.io/joel-bobby/${page==='home'?'':page+'/'}"><meta property="og:image" content="https://parthawe.github.io/joel-bobby/assets/portrait.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${root}favicon.svg"><link rel="preload" href="${root}assets/fonts/manrope-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${root}styles.css?v=20260909b"><link rel="stylesheet" href="${root}motion.css?v=20260909b"><script src="${root}app.js?v=20260909b" defer></script><script src="${root}motion.js?v=20260909b" defer></script>${page==='about'?`<link rel="stylesheet" href="${root}guitar.css?v=20260909b"><script type="module" src="${root}guitar.js?v=20260909b"></script>`:''}<script type="application/ld+json">{"@context":"https://schema.org","@type":"Person","name":"Joel Bobby","alternateName":"Joel Joshua Bobby","jobTitle":"Musician, Record Producer and Audio Engineer","url":"https://parthawe.github.io/joel-bobby/","sameAs":["https://www.linkedin.com/in/joelbobby/","https://www.instagram.com/joel_bobby_009/"]}</script></head>
<body class="page-${page}" data-root="${root}" data-page="${page}">
<!-- THESIS: A photographic sound-engineer portfolio, guided by Joe Joaquin, Serban Ghenea and Craig Bauer. OWN-WORLD: charcoal, warm paper, muted brass; Manrope type and original artwork. STORY: meet Joel, hear records, inspect precise credits, make contact. FIRST VIEWPORT: home pairs Joel's two-line name and manual preview with a cropped portrait entrance; each inner page opens its own subject. FORM: five real static pages with shared navigation, native links and a manual listening player. Reference-led brief governs seed d209f56e. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md -->
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="wordmark" href="${root}" aria-label="Joel Bobby, home">JOEL BOBBY<span>Music & sound</span></a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="navigation">${icon('list')}</button><nav id="navigation" aria-label="Main navigation">${nav}</nav></header>
<main id="main">${content(root)}</main>
${page!=='contact'?`<section class="site-cta"><div><h2>Have something in mind?</h2><p>A record, a live set, or an idea. Let’s talk.</p></div><a class="button" href="${url('contact',root)}">Start a conversation ${icon('arrow-up-right')}</a></section>`:''}
<footer class="site-footer"><div class="footer-top"><a class="footer-name" href="${root}">Joel Bobby<span>Musician · Producer · Engineer</span></a><nav aria-label="Footer navigation">${nav}</nav></div><div class="footer-bottom"><span>© <span id="year">2026</span> Joel Bobby</span><span>Brooklyn, New York</span><div><a href="https://www.instagram.com/joel_bobby_009/" ${external}>Instagram ${icon('arrow-up-right')}</a><a href="https://www.linkedin.com/in/joelbobby/" ${external}>LinkedIn ${icon('arrow-up-right')}</a></div></div></footer>
<aside class="player" id="player" aria-label="Audio preview player" hidden><img id="player-art" src="${root}assets/pills.webp" alt="" width="48" height="48"><div class="player-track"><strong id="player-title"></strong><span id="player-artist"></span></div><button id="player-toggle" aria-label="Pause preview">${icon('pause')}</button><span id="player-time">0:00</span><div class="waveform-control"><canvas id="waveform" aria-hidden="true"></canvas><input id="player-seek" type="range" min="0" max="30" value="0" step="0.1" aria-label="Preview playback position"></div><span class="player-preview">30s preview</span><button id="player-close" aria-label="Close player">${icon('x')}</button><p class="player-error" id="player-error" role="status"></p></aside><audio id="audio" preload="none"></audio></body></html>`;
}
